server:
  port: 8888
spring:  application:    name: configserver
  cloud:    config:      server:        git:          uri: https://github.com/RonaldQin/Spring-Cloud-Study.git
          search-paths: config
          username: RonaldQin
          password: 8737691qb^-^
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka